# Основные настройки плагина.
settings:
  # Включен ли плагин?
  enabled: true
  # Отправлять статистику об использовании? (анонимно)
  metrics: true
  # Форматирование сообщений.
  # legacy - &цвет.
  # minimessage - <цвет>.
  # Подробнее о MiniMessage: https://docs.papermc.io/adventure/minimessage/format/
  colorizer: legacy
  # Поддержка PlaceholderAPI.
  papi_support: true
  # Право, которое нужно для перезагрузки плагина. (по умолчанию "ecr.reload")
  permission_for_reload: "ecr.reload"
  # Замена символа в командах.
  command_replace: true
  # Сообщения плагина.
  # Если вы не хотите, чтобы сообщение было отправлено, напишите вместо значения null или nil.
  messages:
    no_perms: nil
    reloaded: "&#66FFE0&lEmoji | &#71FF49Плагин успешно перезагружен"
  # Настройки эмодзи.
  emojis:
    ':)': '☺'
    ':(': '☹'
  #
  # emojis:
  #   'что заменять': 'на что заменять'
  #
  # = ИЛИ =
  #
  # emojis:
  #   'что заменять':
  #     value: 'на что заменять'
  #     perm: 'право, которое нужно для замены символа на эмодзи'
  #
