# Основные настройки плагина.
settings:
  # Право, которое нужно для перезагрузки плагина. (по умолчанию "ecr.reload")
  permission-for-reload: "ecr.reload"
  # Сообщения плагина.
  # Если вы не хотите, чтобы сообщение было отправлено, напишите вместо значения null или nil.
  # Поддерживает только Legacy цвета.
  messages:
    no-perms: nil
    reloaded: "&aПлагин &eEmojiChatReplacer&a перезагружен!"
  # Настройки эмодзи.
  # -------------------
  # emojis:
  #   'что заменять': 'на что заменять'
  # -------------------
  emojis:
    ':)': '☺'
    ':(': '☹'
